<?php 
    $team = [
        [
            'name' => 'Andrew Woll',
            'title' => 'Software Engineer',
            'prof' => 'Video Game Developer',
            'company' => 'Hypixel',
            'email' => 'wolla2@nku.edu',
            'intro' => 'Welcome to my information page. A little to know about me is that I am a senior at NKU studying Applied Software Engineering. In 2018, I received my Communication Studies degree so I am a returning student. Artificial Intelligence and machine learning are two areas of expertise I would like to learn more about in the future.',
            'blurb' => "Life is like a box of chocolates. You never know what you're gonna get.",
            'skill1' => 'Object-Oriented Programming',
            'skill1_perc' => '85',
            'skill2' => 'Full-Stack Development',
            'skill2_perc' => '70',
            'skill3' => 'Software Design',
            'skill3_perc' => '77',
            'funfact' => 'I am an Eagle Scout so I love being outdoors. I love to go to music festivals and travel in general. My dream as a software engineer is to produce and develop my own roleplaying game.',
            'year' => 4,
            'dob' => "1996-05-15",
        ],
        [
            'name' => 'Ben Davis',
            'title' => 'Businessman',
            'prof' => 'CEO',
            'company' => 'Real Good Business',
            'email' => 'davisb@rgb.com',
            'intro' => 'I am an extrodinary businessman.',
            'blurb' => "YOU CAN'T HANDLE THE TRUTH!",
            'skill1' => 'Business',
            'skill1_perc' => '100',
            'skill2' => 'Maniging Business',
            'skill2_perc' => '100',
            'skill3' => 'Advising Business',
            'skill3_perc' => '100',
            'funfact' => 'Taxbrokers love me and business people wanna be me.',
            'year' => 3,
            'dob' => "1912-1-11",
        ],
        [
            'name' => 'Jeff Coolsberry',
            'title' => 'Cool Guy',
            'prof' => 'Professor of Coolness',
            'company' => 'University of Cool',
            'email' => 'coolsberryj@uoc.edu',
            'intro' => "Don't be wickity wack, maaan. We're cool around here.",
            'blurb' => 'Far out, maaan.',
            'skill1' => 'Being Cool',
            'skill1_perc' => '99',
            'skill2' => 'Looking Cool',
            'skill2_perc' => '100',
            'skill3' => 'Staying Cool',
            'skill3_perc' => '90',
            'funfact' => "Don't forget that I'm the coolest!",
            'year' => 2,
            'dob' => "0001-01-01",
        ]
    ];
?>